name: neuralwalker
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pytorch=2.0.*
  - pytorch-cuda=11.8
  - pyg=2.3.*
  - cython=3.0.9
  - pandas
  - einops
  - lightning
  - scikit-learn
  - cuda-nvcc=11.8
  - mkl=2022.2.1
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.0.0+cu118.html
    - pyprojroot
    - easydict 
    - hydra-core
    - torch-scatter
    - causal-conv1d==1.2.0.post2
    - mamba-ssm==1.2.0.post1
    - ogb