name: neuralwalker
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - numpy
  - scipy
  - pytorch=2.2.*
  - pytorch-cuda=11.8
  - pyg>=2.3
  - cython=3.0.9
  - pandas
  - einops
  - lightning
  - scikit-learn
  - cuda-nvcc=11.8
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.2.0+cu118.html
    - pyprojroot
    - easydict 
    - hydra-core
    - torch-scatter
    - causal-conv1d>=1.2.0
    - mamba-ssm==1.2.0.post1
    - ogb