# @package _global_

debug: true

logs:
  prefix: logs_debug/${dataset.name}

compute:
  accelerator: cpu
  precision: 32

training:
  epochs: 10
  weight_decay: 0.0
  batch_size: 4
  warmup: 1
  num_workers: 0
  pin_memory: false

test_runs: 2
